---
jobs:
- name: update-opencontrol-website
  public: true
  serial: true
  plan:
  - get: git-opencontrol-website
    trigger: true
  - task: rebuild-mkdocs
    config:
      platform: linux
      image: "docker:///nate/mkdocs"
      inputs:
        - name: git-opencontrol-website
          path: /mkdocs
      run:
        path: /run.sh
      #   args: ["build"]
  - put: opencontrol-website
    params:
      manifest: rebuild-mkdocs/manifest.yml
      path: rebuild-mkdocs/site

resources:
- name: git-opencontrol-website
  type: git
  source:
    uri: https://github.com/opencontrol/opencontrol.github.io.git

- name: opencontrol-website
  type: cf
  source:
    api: https://api.run.pivotal.io
    username: josh@beanpatch.org
    password: {{PWS_PASSWORD}}
    organization: beanpatch
    space: opencontrol
    skip_cert_check: false
